[package]
name = "breakpad"
version = "0.1.0"
authors = ["Jan Michael Auer"]
build = "build.rs"

[dependencies]
error-chain = "0.10"
uuid = { version = "0.5", features = ["use_std"] }

[dev-dependencies]
difference = "1.0"
